CREATE TABLE `configuracoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`empresa` text,
	`cnpj` varchar(20),
	`regimeTributario` varchar(50),
	`icmsDefault` int NOT NULL DEFAULT 18,
	`pisDefault` int NOT NULL DEFAULT 165,
	`cofinsDefault` int NOT NULL DEFAULT 760,
	`ipiDefault` int NOT NULL DEFAULT 0,
	`issDefault` int NOT NULL DEFAULT 0,
	`margemDefault` int NOT NULL DEFAULT 20,
	`endereco` text,
	`cep` varchar(10),
	`celular` varchar(20),
	`email` varchar(320),
	`banco` varchar(10),
	`agencia` varchar(10),
	`contaCorrente` varchar(30),
	`validadePropostadias` int NOT NULL DEFAULT 30,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `configuracoes_id` PRIMARY KEY(`id`),
	CONSTRAINT `configuracoes_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `itensPrecificacao` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`processoId` int NOT NULL,
	`item` varchar(10) NOT NULL,
	`descricao` text NOT NULL,
	`quantidade` int NOT NULL,
	`valorUnitario` int NOT NULL,
	`icms` int NOT NULL,
	`pis` int NOT NULL,
	`cofins` int NOT NULL,
	`ipi` int NOT NULL,
	`iss` int NOT NULL,
	`margem` int NOT NULL,
	`fretePercentual` int NOT NULL,
	`linkFornecedor` text,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `itensPrecificacao_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `processos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`data` varchar(10) NOT NULL,
	`numero` varchar(50) NOT NULL,
	`descricao` text NOT NULL,
	`status` enum('Em Andamento','Ganho','Perdido','Finalizado') NOT NULL DEFAULT 'Em Andamento',
	`link` text,
	`dataLimite` varchar(10),
	`horarioLimite` varchar(5),
	`resultado` text,
	`observacoes` text,
	`nomeOrgao` text,
	`numeroOrgao` varchar(50),
	`numeroPregao` varchar(50),
	`anoPregao` varchar(4),
	`arquivado` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `processos_id` PRIMARY KEY(`id`)
);
